//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('ChatSettings')
export class ChatSettingsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('bool', { nullable: true })
  notifications: boolean;

  @Column('integer', { nullable: true })
  autoDelete: number;

  @Column('integer', { nullable: true })
  theme: number;

  @Column('text', { nullable: true })
  languagePreference: string;
}
