//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('LearningManagementSystems')
export class LearningManagementSystemsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  name: string;

  @Column('text', { nullable: true })
  type: string;

  @Column('text', { nullable: true })
  source: string;

  @Column('text', { nullable: true })
  accessLevel: string;
}
