//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Media')
export class MediaEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  videoOrAudioUpload: string;

  @Column('text', { nullable: true })
  images: string;
}
