//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Messages')
export class MessagesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  send: string;

  @Column('text', { nullable: true })
  upload: string;

  @Column('text', { nullable: true })
  attach: string;

  @Column('text', { nullable: true })
  image: string;
}
