//Source code generated by AppGPT (www.appgpt.tech)
import { Admin, Resource, CustomRoutes } from 'react-admin';
import { customDataProvider } from './dataProvider';
import fakeDataProvider from 'ra-data-fakerest';
import { Dashboard } from './dashboard';
import { authProvider, apInitialize } from './authProvider';
import { i18nProvider } from './i18nProvider';
import LoginPage, { Login } from './Login';
import data from './data';
import {
  MessagesList,
  MessagesCreate,
  MessagesEdit,
} from './resources/Messages';
import { CallsList, CallsCreate, CallsEdit } from './resources/Calls';
import { MediaList, MediaCreate, MediaEdit } from './resources/Media';
import {
  LearningManagementSystemsList,
  LearningManagementSystemsCreate,
  LearningManagementSystemsEdit,
} from './resources/LearningManagementSystems';
import {
  UserPreferencesList,
  UserPreferencesCreate,
  UserPreferencesEdit,
} from './resources/UserPreferences';
import {
  ChatHistoryList,
  ChatHistoryCreate,
  ChatHistoryEdit,
} from './resources/ChatHistory';
import {
  ChatSettingsList,
  ChatSettingsCreate,
  ChatSettingsEdit,
} from './resources/ChatSettings';
import { ThemesList, ThemesCreate, ThemesEdit } from './resources/Themes';
import MessagesIcon from '@mui/icons-material/Message';
import CallsIcon from '@mui/icons-material/Call';
import MediaIcon from '@mui/icons-material/PermMedia';
import LearningManagementSystemsIcon from '@mui/icons-material/School';
import UserPreferencesIcon from '@mui/icons-material/Settings';
import ChatHistoryIcon from '@mui/icons-material/History';
import ChatSettingsIcon from '@mui/icons-material/Settings';
import ThemesIcon from '@mui/icons-material/Brightness6';
// SUPERTOKENS
import React from 'react';
import SuperTokens, {
  SuperTokensWrapper,
  getSuperTokensRoutesForReactRouterDom,
} from 'supertokens-auth-react';
import ThirdPartyPasswordless from 'supertokens-auth-react/recipe/thirdpartypasswordless';
import Session from 'supertokens-auth-react/recipe/session';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import * as reactRouterDom from 'react-router-dom';
let sessionFn = Session.init();
SuperTokens.init({
  appInfo: {
    appName: import.meta.env.VITE_SUPERTOKENS_APPNAME,
    apiDomain: import.meta.env.VITE_BACKEND_DOMAIN,
    websiteDomain: import.meta.env.VITE_SUPERTOKENS_WEBSITEDOMAIN,
    apiBasePath: import.meta.env.VITE_BACKEND_APIPATH + '/auth',
    websiteBasePath: import.meta.env.VITE_SUPERTOKENS_WEBSITEBASEPATH,
  },
  recipeList: [
    ThirdPartyPasswordless.init({
      contactMethod: 'EMAIL',
      signInUpFeature: {
        providers: [
          ThirdPartyPasswordless.Github.init(),
          //ThirdPartyPasswordless.Google.init(),
          //ThirdPartyPasswordless.Facebook.init(),
          //ThirdPartyPasswordless.Apple.init(),
        ],
      },
    }),
    sessionFn,
  ],
});
apInitialize(Session);
// END SUPERTOKENS
let dataProvider: any;
if (import.meta.env.VITE_USE_BACKEND_DATA === 'true') {
  dataProvider = customDataProvider(
    import.meta.env.VITE_BACKEND_DOMAIN +
      import.meta.env.VITE_BACKEND_APIPATH +
      '/proxy',
  );
} else {
  dataProvider = fakeDataProvider(data.defaultData);
}

const App = () => (
  <SuperTokensWrapper>
    <BrowserRouter basename="/a792abfac">
      <Admin
        authProvider={
          import.meta.env.VITE_ENVIRONMENT != 'DEV' ? authProvider : undefined
        }
        requireAuth
        loginPage={LoginPage}
        dataProvider={dataProvider}
        i18nProvider={i18nProvider}
        dashboard={Dashboard}
      >
        <Resource
          name="Messages"
          options={{ label: 'Messages' }}
          list={MessagesList}
          create={MessagesCreate}
          edit={MessagesEdit}
          recordRepresentation="send"
          icon={MessagesIcon}
        />
        <Resource
          name="Calls"
          options={{ label: 'Calls' }}
          list={CallsList}
          create={CallsCreate}
          edit={CallsEdit}
          recordRepresentation="callButton"
          icon={CallsIcon}
        />
        <Resource
          name="Media"
          options={{ label: 'Media' }}
          list={MediaList}
          create={MediaCreate}
          edit={MediaEdit}
          recordRepresentation="videoOrAudioUpload"
          icon={MediaIcon}
        />
        <Resource
          name="LearningManagementSystems"
          options={{ label: 'Learning Management Systems' }}
          list={LearningManagementSystemsList}
          create={LearningManagementSystemsCreate}
          edit={LearningManagementSystemsEdit}
          recordRepresentation="name"
          icon={LearningManagementSystemsIcon}
        />
        <Resource
          name="UserPreferences"
          options={{ label: 'User Preferences' }}
          list={UserPreferencesList}
          create={UserPreferencesCreate}
          edit={UserPreferencesEdit}
          recordRepresentation="sessionSetting"
          icon={UserPreferencesIcon}
        />
        <Resource
          name="ChatHistory"
          options={{ label: 'Chat History' }}
          list={ChatHistoryList}
          create={ChatHistoryCreate}
          edit={ChatHistoryEdit}
          recordRepresentation="history"
          icon={ChatHistoryIcon}
        />
        <Resource
          name="ChatSettings"
          options={{ label: 'Chat Settings' }}
          list={ChatSettingsList}
          create={ChatSettingsCreate}
          edit={ChatSettingsEdit}
          recordRepresentation="notifications"
          icon={ChatSettingsIcon}
        />
        <Resource
          name="Themes"
          options={{ label: 'Themes' }}
          list={ThemesList}
          create={ThemesCreate}
          edit={ThemesEdit}
          recordRepresentation="themeOption"
          icon={ThemesIcon}
        />
        <CustomRoutes noLayout>
          {/*This renders the login UI on the /auth route*/}
          {getSuperTokensRoutesForReactRouterDom(reactRouterDom)}
          {/*Your app routes*/}
        </CustomRoutes>
      </Admin>
    </BrowserRouter>
  </SuperTokensWrapper>
);

export default App;
