//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Messages: {
      name: 'Messages',
      fields: {
        send: 'Send',
        upload: 'Upload',
        attach: 'Attach',
        image: 'Image',
        id: 'id',
      },
    },
    Calls: { name: 'Calls', fields: { callButton: 'Call Button', id: 'id' } },
    Media: {
      name: 'Media',
      fields: {
        videoOrAudioUpload: 'Video Or Audio Upload',
        images: 'Images',
        id: 'id',
      },
    },
    LearningManagementSystems: {
      name: 'Learning Management Systems',
      fields: {
        name: 'Name',
        type: 'Type',
        source: 'Source',
        accessLevel: 'Access Level',
        id: 'id',
      },
    },
    UserPreferences: {
      name: 'User Preferences',
      fields: {
        sessionSetting: 'Session Setting',
        llmResponse: 'Llm Response',
        id: 'id',
      },
    },
    ChatHistory: {
      name: 'Chat History',
      fields: { history: 'History', id: 'id' },
    },
    ChatSettings: {
      name: 'Chat Settings',
      fields: {
        notifications: 'Notifications',
        autoDelete: 'Auto Delete',
        theme: 'Theme',
        languagePreference: 'Language Preference',
        id: 'id',
      },
    },
    Themes: {
      name: 'Themes',
      fields: { themeOption: 'Theme Option', id: 'id' },
    },
  },
};
const frResources = {
  resources: {
    Messages: {
      name: 'Messages (fr)',
      fields: {
        send: 'Send (fr)',
        upload: 'Upload (fr)',
        attach: 'Attach (fr)',
        image: 'Image (fr)',
        id: 'id',
      },
    },
    Calls: {
      name: 'Calls (fr)',
      fields: { callButton: 'Call Button (fr)', id: 'id' },
    },
    Media: {
      name: 'Media (fr)',
      fields: {
        videoOrAudioUpload: 'Video Or Audio Upload (fr)',
        images: 'Images (fr)',
        id: 'id',
      },
    },
    LearningManagementSystems: {
      name: 'Learning Management Systems (fr)',
      fields: {
        name: 'Name (fr)',
        type: 'Type (fr)',
        source: 'Source (fr)',
        accessLevel: 'Access Level (fr)',
        id: 'id',
      },
    },
    UserPreferences: {
      name: 'User Preferences (fr)',
      fields: {
        sessionSetting: 'Session Setting (fr)',
        llmResponse: 'Llm Response (fr)',
        id: 'id',
      },
    },
    ChatHistory: {
      name: 'Chat History (fr)',
      fields: { history: 'History (fr)', id: 'id' },
    },
    ChatSettings: {
      name: 'Chat Settings (fr)',
      fields: {
        notifications: 'Notifications (fr)',
        autoDelete: 'Auto Delete (fr)',
        theme: 'Theme (fr)',
        languagePreference: 'Language Preference (fr)',
        id: 'id',
      },
    },
    Themes: {
      name: 'Themes (fr)',
      fields: { themeOption: 'Theme Option (fr)', id: 'id' },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
